export const GET_ALL_CARS_REQUEST = "GET_ALL_CARS_REQUEST";
export const GET_ALL_CARS_SUCCESS = "GET_ALL_CARS_SUCCESS";
export const GET_ALL_CARS_ERROR = "GET_ALL_CARS_ERROR";

export const CREATE_CAR_REQUEST = "CREATE_CAR_REQUEST";
export const CREATE_CAR_SUCCESS = "CREATE_CAR_SUCCESS";
export const CREATE_CAR_ERROR = "CREATE_CAR_ERROR";

export const EDIT_CAR_REQUEST = "EDIT_CAR_REQUEST";
export const EDIT_CAR_SUCCESS = "EDIT_CAR_SUCCESS";
export const EDIT_CAR_ERROR = "EDIT_CAR_ERROR";

export const DELETE_CAR_REQUEST = "DELETE_CAR_REQUEST";
export const DELETE_CAR_SUCCESS = "DELETE_CAR_SUCCESS";
export const DELETE_CAR_ERROR = "DELETE_CAR_ERROR";
